- name: "{{ module['mod'] }} - Remove mod"
  file: 
    path: "{{ application_folder_destination }}/mod/{{ module['mod'] }}"
    state: "absent"
  ignore_errors: "yes"
- name: "{{ module['mod'] }} - Download new mod"
  get_url:
    url: "{{ module['url'] }}"
    dest: "{{ application_folder_destination }}/mod/download_module"
- name: "{{ module['mod'] }} - Unarchive mod"
  tags:
    - "uncheckable"
  unarchive:
    src: "{{ application_folder_destination }}/mod/download_module"
    dest: "{{ application_folder_destination }}/mod"
    owner: "{{ owner_destination }}"
    group: "{{ group_destination }}"
    remote_src: "yes"
- name: "{{ module['mod'] }} - Remove archive"
  file:
    path: "{{ application_folder_destination }}/mod/download_module"
    state: "absent"
- name: "{{ module['mod'] }} - Rename folder"
  tags:
    - "uncheckable"
  command: "mv {{ module['rename_from'] }} {{ module['rename_to'] }} chdir={{ application_folder_destination }}/mod"
  when: "module['rename_from'] is defined and module['rename_to'] is defined"
- name: "{{ module['mod'] }} - Refresh plugins"
  tags:
    - "uncheckable"
  command: "{{ php_command }} vendor/bin/elgg-cli plugin:list -r chdir={{ application_folder_destination }}"
